fix: builder error
error: could not format file
/nix/store/nmkp9qgraazj3vaxsdfawsmisi6wkf07-init.lua: error parsing:
error occurred while creating ast: unexpected token `<`. (starting from
line 166, character 260 and ending on line 166, character 261).
It was due to toggleterm's open_mapping keymapping, nixvim refactored
the original way of changing the mapping key, this commit fixes it.